version: "3.8"
services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: fota
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 8QYRjyZGxMUyT3KhGX
  app:
    image: man-backend-challenge-app-layer
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db